### ISSUE TITLE
HighCharts

### ISSUE THREAD

**Issue by carlskii** [csbun/gitbook-plugin-chart#1]
Hi, 

I'm trying to workout how to create a plugin for GitBook. The documentation seem a little sparse. 

Could you give me a few pointers as to how I could modify your example to use highcharts instead of C3? 

Thanks

**Comment by csbun** [comment]
You might fork my repo and then modify [index.js](https://github.com/csbun/gitbook-plugin-chart/blob/master/index.js) at [L11](https://github.com/csbun/gitbook-plugin-chart/blob/master/index.js#L11), [L33](https://github.com/csbun/gitbook-plugin-chart/blob/master/index.js#L33) and [L67](https://github.com/csbun/gitbook-plugin-chart/blob/master/index.js#L67) to highcharts.

Maybe i can add some option for chosing C3, highcharts or somemore...

**Comment by carlskii** [comment]
Hey Hans, 

I'll give your suggestion a try.

> Maybe i can add some option for chosing C3, highcharts or somemore... 

Yes this would be most welcome.

Also, it would be nice to move most of the chart config to another file rather than having to include it within the markup. That way you can maybe just use markup in YAML like this.

```
## Chart 1 here

Tertrewewt erw

{%% 
id: c1
categories: [cars, trains, buses, planes, trams]
competition:
  comp1: [20, 8, 1, 2, 9]
  comp2: [5, 8, 1, 2, 9]
  comp3: [5, 8, 1, 2, 9]
  comp4: [8, 5, 1, 2, 9]
  comp5: [5, 8, 1, 2, 9]
  comp6: [9, 9, 1, 2, 9]
  comp7: [2, 5, 5, 5, 9]
  comp8: [5, 8, 1, 2, 9]
  comp9: [5, 5, 3, 3, 9]
  comp10: [8, 5, 1, 2, 9]
title: Today
ven: [1,2,3,4,20]
%%}
```
