### ISSUE TITLE
Chart data in YAML format.

### ISSUE THREAD

**Issue by carlskii** [csbun/gitbook-plugin-chart#2]
Hi,

I'm looking into forking your repo in order to use YAML in the Git Book markup as oppose to specifying  the entire chart in its JSON format. 

I would like to move the chart configs to separate templates and then provide only the chart data. e.g. 

I was able to successfully create a block that looks like this: 

```yaml
{%% 
categories: [cars, trains, buses, planes, trams]
competition:
  comp1: [20, 8, 1, 2, 9]
  comp2: [5, 8, 1, 2, 9]
  comp3: [5, 8, 1, 2, 9]
  comp4: [8, 5, 1, 2, 9]
  comp5: [5, 8, 1, 2, 9]
  comp6: [9, 9, 1, 2, 9]
  comp7: [2, 5, 5, 5, 9]
  comp8: [5, 8, 1, 2, 9]
  comp9: [5, 5, 3, 3, 9]
  comp10: [8, 5, 1, 2, 9]
title: Today
ven: [1,2,3,4,20]
%%}
``` 

I then used  [js-yaml](https://github.com/nodeca/js-yaml) to parse the file into a JSON structure that looks like this.

```json
{
	"id": "c1",
	"categories": ["cars", "trains", "buses", "planes", "trams"],
	"competition": {
		"comp1": [20, 8, 1, 2, 9],
		"comp2": [5, 8, 1, 2, 9],
		"comp3": [5, 8, 1, 2, 9],
		"comp4": [8, 5, 1, 2, 9],
		"comp5": [5, 8, 1, 2, 9],
		"comp6": [9, 9, 1, 2, 9],
		"comp7": [2, 5, 5, 5, 9],
		"comp8": [5, 8, 1, 2, 9],
		"comp9": [5, 5, 3, 3, 9],
		"comp10": [8, 5, 1, 2, 9]
	},
	"title": "Today",
	"ven": [1, 2, 3, 4, 20]
}
```

However, I'm a little stuck from this point onwards. I could do with a couple of pointers regarding the following:

1. Creating the Chart template 
2. Adding the JSON data to the chart template
3. Rendering the template to the `<div id="${id}"></div>` tag in the page.

Is this something you provide a little guidance on ?

**Comment by csbun** [comment]
Support YAML in [0.1.1](https://github.com/csbun/gitbook-plugin-chart/releases/tag/0.1.1):

In this case, you have to declare `yaml` as a `format`:

```
{% chart format="yaml" %}
# yaml here
{% endchart %}
```

**Comment by carlskii** [comment]
I just tried the YAML format, but it doesnt seem to render the chart. However it does render the highcharts frame. This is what I used. 

```{% chart format="yaml" %}
data:
    type: bar
    columns:
        - [data1, 30, 200, 100, 400, 150, 250]
        - [data2, 50, 20, 10, 40, 15, 25]
    axes:
        data2: y2
axis:
    y2:
        show: true
```{% endchart %}

When I ran the gitbook server it did return the output though. e.g.

```
{
    "data": {
        "type": "bar",
        "columns": [
            [
                "data1",
                30,
                200,
                100,
                400,
                150,
                250
            ],
            [
                "data2",
                50,
                20,
                10,
                40,
                15,
                25
            ]
        ],
        "axes": {
            "data2": "y2"
        }
    },
    "axis": {
        "y2": {
            "show": true
        }
    }
}
finish!
info: generation is finished 
```

**Comment by csbun** [comment]
The example in YAML is for `C3.js`, you should try it a `highcharts` way, something maybe:

```
{% chart format="yaml" %}
chart:
    type: bar
title:
    text: Fruit Consumption
xAxis:
    categories: 
        - Apples
        - Bananas
        - Oranges
yAxis:
    title:
        text: Fruit eaten
series:
    - { name: Jane, data: [1, 0, 4] }
    - { name: John, data: [5, 7, 3] }
{% endchart %}
```

PS. sorry i forgot to delete the debug line.
